### PR TITLE
added redme file

### PR DESCRIPTION
**Pull request by Rutwik187**
Completed the readme config file. But for this to show on your profile section **you need to paste this readme file in the repository with the same name as your GitHub user name.**

also, replace the social media links with your handle. 

Please merge this pull request. I will be helping you if you face any issues.

image

### CODE REVIEW

**Comment by gargvivek2003** [comment]
image

could you add these and view count

**Comment by Rutwik187** [comment]
I can add all this tags inside social media handle and link them. Will it work?

**Comment by Rutwik187** [comment]
And also I had added the view count.

**Comment by gargvivek2003** [comment]
surely it will work

**Comment by gargvivek2003** [comment]
have you posted new file

**Comment by Rutwik187** [comment]
> have you posted new file

I am working on social media links. I will update you shortly.

**Comment by gargvivek2003** [comment]
ok

**Comment by gargvivek2003** [comment]
in techstacks instead of nodejs, mongodb, next and react can you add bootstrap,php,c,html,mysql,oracle,

**Comment by Rutwik187** [comment]
added all the changes.

image

**Comment by gargvivek2003** [comment]
ok
share the file now

**Pull request merged**
